In [40]:
path = r"C:\Users\Ariana\Desktop\anaconda\Projects\ames.csv"

In [41]:
import numpy as np
import pandas as pd

In [42]:
df = pd.read_csv(path)

In [43]:
df.shape

(2930, 81)

In [44]:
df.columns.tolist()

['MS_SubClass',
 'MS_Zoning',
 'Lot_Frontage',
 'Lot_Area',
 'Street',
 'Alley',
 'Lot_Shape',
 'Land_Contour',
 'Utilities',
 'Lot_Config',
 'Land_Slope',
 'Neighborhood',
 'Condition_1',
 'Condition_2',
 'Bldg_Type',
 'House_Style',
 'Overall_Qual',
 'Overall_Cond',
 'Year_Built',
 'Year_Remod_Add',
 'Roof_Style',
 'Roof_Matl',
 'Exterior_1st',
 'Exterior_2nd',
 'Mas_Vnr_Type',
 'Mas_Vnr_Area',
 'Exter_Qual',
 'Exter_Cond',
 'Foundation',
 'Bsmt_Qual',
 'Bsmt_Cond',
 'Bsmt_Exposure',
 'BsmtFin_Type_1',
 'BsmtFin_SF_1',
 'BsmtFin_Type_2',
 'BsmtFin_SF_2',
 'Bsmt_Unf_SF',
 'Total_Bsmt_SF',
 'Heating',
 'Heating_QC',
 'Central_Air',
 'Electrical',
 'First_Flr_SF',
 'Second_Flr_SF',
 'Low_Qual_Fin_SF',
 'Gr_Liv_Area',
 'Bsmt_Full_Bath',
 'Bsmt_Half_Bath',
 'Full_Bath',
 'Half_Bath',
 'Bedroom_AbvGr',
 'Kitchen_AbvGr',
 'Kitchen_Qual',
 'TotRms_AbvGrd',
 'Functional',
 'Fireplaces',
 'Fireplace_Qu',
 'Garage_Type',
 'Garage_Finish',
 'Garage_Cars',
 'Garage_Area',
 'Garage_Qual',
 'Garage_Cond',
 'Paved_Drive',
 'Wood_Deck_SF',
 'Open_Porch_SF',
 'Enclosed_Porch',
 'Three_season_porch',
 'Screen_Porch',
 'Pool_Area',
 'Pool_QC',
 'Fence',
 'Misc_Feature',
 'Misc_Val',
 'Mo_Sold',
 'Year_Sold',
 'Sale_Type',
 'Sale_Condition',
 'Sale_Price',
 'Longitude',
 'Latitude']

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 81 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   MS_SubClass         2930 non-null   object
 1   MS_Zoning           2930 non-null   object
 2   Lot_Frontage        2930 non-null   int64
 3   Lot_Area            2930 non-null   int64
 4   Street              2930 non-null   object
 5   Alley               2930 non-null   object
 6   Lot_Shape           2930 non-null   object
 7   Land_Contour        2930 non-null   object
 8   Utilities           2930 non-null   object
 9   Lot_Config          2930 non-null   object
 10  Land_Slope          2930 non-null   object
 11  Neighborhood        2930 non-null   object
 12  Condition_1         2930 non-null   object
 13  Condition_2         2930 non-null   object
 14  Bldg_Type           2930 non-null   object
 15  House_Style         2930 non-null   object
 16  Overall_Qual        2930 non-null   object
 17  Overall_Cond        2930 non-null   object
 18  Year_Built          2930 non-null   int64
 19  Year_Remod_Add      2930 non-null   int64
 20  Roof_Style          2930 non-null   object
 21  Roof_Matl           2930 non-null   object
 22  Exterior_1st        2930 non-null   object
 23  Exterior_2nd        2930 non-null   object
 24  Mas_Vnr_Type        1155 non-null   object
 25  Mas_Vnr_Area        2930 non-null   int64
 26  Exter_Qual          2930 non-null   object
 27  Exter_Cond          2930 non-null   object
 28  Foundation          2930 non-null   object
 29  Bsmt_Qual           2930 non-null   object
 30  Bsmt_Cond           2930 non-null   object
 31  Bsmt_Exposure       2930 non-null   object
 32  BsmtFin_Type_1      2930 non-null   object
 33  BsmtFin_SF_1        2930 non-null   int64
 34  BsmtFin_Type_2      2930 non-null   object
 35  BsmtFin_SF_2        2930 non-null   int64
 36  Bsmt_Unf_SF         2930 non-null   int64
 37  Total_Bsmt_SF       2930 non-null   int64
 38  Heating             2930 non-null   object
 39  Heating_QC          2930 non-null   object
 40  Central_Air         2930 non-null   object
 41  Electrical          2930 non-null   object
 42  First_Flr_SF        2930 non-null   int64
 43  Second_Flr_SF       2930 non-null   int64
 44  Low_Qual_Fin_SF     2930 non-null   int64
 45  Gr_Liv_Area         2930 non-null   int64
 46  Bsmt_Full_Bath      2930 non-null   int64
 47  Bsmt_Half_Bath      2930 non-null   int64
 48  Full_Bath           2930 non-null   int64
 49  Half_Bath           2930 non-null   int64
 50  Bedroom_AbvGr       2930 non-null   int64
 51  Kitchen_AbvGr       2930 non-null   int64
 52  Kitchen_Qual        2930 non-null   object
 53  TotRms_AbvGrd       2930 non-null   int64
 54  Functional          2930 non-null   object
 55  Fireplaces          2930 non-null   int64
 56  Fireplace_Qu        2930 non-null   object
 57  Garage_Type         2930 non-null   object
 58  Garage_Finish       2930 non-null   object
 59  Garage_Cars         2930 non-null   int64
 60  Garage_Area         2930 non-null   int64
 61  Garage_Qual         2930 non-null   object
 62  Garage_Cond         2930 non-null   object
 63  Paved_Drive         2930 non-null   object
 64  Wood_Deck_SF        2930 non-null   int64
 65  Open_Porch_SF       2930 non-null   int64
 66  Enclosed_Porch      2930 non-null   int64
 67  Three_season_porch  2930 non-null   int64
 68  Screen_Porch        2930 non-null   int64
 69  Pool_Area           2930 non-null   int64
 70  Pool_QC             2930 non-null   object
 71  Fence               2930 non-null   object
 72  Misc_Feature        106 non-null    object
 73  Misc_Val            2930 non-null   int64
 74  Mo_Sold             2930 non-null   int64
 75  Year_Sold           2930 non-null   int64
 76  Sale_Type           2930 non-null   object
 77  Sale_Condition      2930 non-null   object
 78  Sale_Price          2930 non-null   int64
 79  Longitude           2930 non-null   float64
 80  Latitude            2930 non-null   float64
dtypes: float64(2), int64(33), object(46)
memory usage: 1.8+ MB

In [46]:
missing = df.isna().sum()
missing[missing>0].sort_values(ascending = False)

Misc_Feature    2824
Mas_Vnr_Type    1775
dtype: int64

In [47]:
df["Misc_Feature"].value_counts(dropna = False)

Misc_Feature
NaN     2824
Shed      95
Gar2       5
Othr       4
Elev       1
TenC       1
Name: count, dtype: int64

In [48]:
df["Mas_Vnr_Type"].value_counts(dropna = False)

Mas_Vnr_Type
NaN        1775
BrkFace     880
Stone       249
BrkCmn       25
CBlock        1
Name: count, dtype: int64

In [49]:
df.isna().sum().sum()

np.int64(4599)

In [50]:
missing

MS_SubClass       0
MS_Zoning         0
Lot_Frontage      0
Lot_Area          0
Street            0
                 ..
Sale_Type         0
Sale_Condition    0
Sale_Price        0
Longitude         0
Latitude          0
Length: 81, dtype: int64

In [51]:
missing_percent = (df.isna().sum() / len(df) )* 100

missing_percent[missing_percent > 0].sort_values(ascending =False)

Misc_Feature    96.382253
Mas_Vnr_Type    60.580205
dtype: float64

In [52]:
df_clean = df.copy()

In [53]:
df_clean["Misc_Feature"] = df_clean["Misc_Feature"].fillna("None")
df_clean["Mas_Vnr_Type"] = df_clean["Mas_Vnr_Type"].fillna("None")

In [54]:
df_clean.isna().sum()[df_clean.isna().sum()>0]

Series([], dtype: int64)

In [55]:
df_clean.duplicated().sum()

np.int64(0)

In [56]:
df_clean.dtypes.value_counts()

object     46
int64      33
float64     2
Name: count, dtype: int64

In [57]:
df_clean.describe()

,Lot_Frontage,Lot_Area,Year_Built,Year_Remod_Add,Mas_Vnr_Area,BsmtFin_SF_1,BsmtFin_SF_2,Bsmt_Unf_SF,Total_Bsmt_SF,First_Flr_SF,...,Enclosed_Porch,Three_season_porch,Screen_Porch,Pool_Area,Misc_Val,Mo_Sold,Year_Sold,Sale_Price,Longitude,Latitude
count,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,...,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,57.647782,10147.921843,1971.356314,1984.266553,101.096928,4.177474,49.705461,559.071672,1051.255631,1159.557679,...,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068,-93.642897,42.034482
std,33.499441,7880.017759,30.245361,20.860286,178.634545,2.233372,169.142089,439.540571,440.968018,391.890885,...,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357,0.025700,0.018410
min,0.000000,1300.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000,-93.693153,41.986498
25%,43.000000,7440.250000,1954.000000,1965.000000,0.000000,3.000000,0.000000,219.000000,793.000000,876.250000,...,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000,-93.660217,42.022088
50%,63.000000,9436.500000,1973.000000,1993.000000,0.000000,3.000000,0.000000,465.500000,990.000000,1084.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000,-93.641806,42.034662
75%,78.000000,11555.250000,2001.000000,2004.000000,162.750000,7.000000,0.000000,801.750000,1301.500000,1384.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000,-93.622113,42.049853
max,313.000000,215245.000000,2010.000000,2010.000000,1600.000000,7.000000,1526.000000,2336.000000,6110.000000,5095.000000,...,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000,-93.577427,42.063388

In [58]:
(df_clean["Lot_Frontage"]==0).sum()

np.int64(490)

In [59]:
df_clean[df_clean["Lot_Frontage"]==0][["Lot_Frontage","Lot_Area" ,"Lot_Shape" ,"Neighborhood" ,"Sale_Price"]].head(10)

    Lot_Frontage  Lot_Area           Lot_Shape Neighborhood  Sale_Price
11             0      7980  Slightly_Irregular      Gilbert      185000
14             0      6820  Slightly_Irregular  Stone_Brook      212000
22             0      7500             Regular     Somerset      216000
23             0     11241  Slightly_Irregular   North_Ames      149000
24             0     12537  Slightly_Irregular   North_Ames      149900
55             0      7851             Regular      Gilbert      216500
57             0      7750  Slightly_Irregular      Gilbert      180000
58             0      9505  Slightly_Irregular      Gilbert      222500
74             0      8880  Slightly_Irregular  Sawyer_West      205000
79             0      9453  Slightly_Irregular  Sawyer_West      194500

In [60]:
df_clean[df_clean["Lot_Frontage"] ==0]["Neighborhood"].value_counts()

Neighborhood
North_Ames                                 68
Gilbert                                    54
Sawyer                                     53
College_Creek                              47
Northwest_Ames                             46
Clear_Creek                                24
Mitchell                                   24
Somerset                                   20
Crawford                                   20
Sawyer_West                                19
Northridge                                 17
Edwards                                    16
Timberland                                 15
Brookside                                  13
Old_Town                                   10
Veenker                                     8
Bloomington_Heights                         8
Iowa_DOT_and_Rail_Road                      6
Stone_Brook                                 5
South_and_West_of_Iowa_State_University     4
Meadow_Village                              4
Northridge_Heights                          3
Green_Hills                                 2
Northpark_Villa                             2
Greens                                      1
Landmark                                    1
Name: count, dtype: int64

In [63]:
df_clean.loc[df_clean["Lot_Frontage"] == 0 , "Lot_Frontage"] = np.nan

In [64]:
df_clean["Lot_Frontage"].isna().sum()

np.int64(490)

In [65]:
df_clean["Lot_Frontage"].describe()

count    2440.000000
mean       69.224590
std        23.365335
min        21.000000
25%        58.000000
50%        68.000000
75%        80.000000
max       313.000000
Name: Lot_Frontage, dtype: float64

In [66]:
df_clean["Lot_Frontage"] = df_clean["Lot_Frontage"].fillna(df_clean["Lot_Frontage"].median())

In [74]:
(df_clean["Sale_Price"] <= 0).sum()

np.int64(0)

In [72]:
(df_clean["Lot_Area"] <= 0).sum()

np.int64(0)

In [76]:
(df_clean["Year_Built"] > df_clean["Year_Sold"]).sum()

np.int64(1)

In [78]:
df_clean.loc[df_clean["Year_Built"] > df_clean["Year_Sold"] , ["Year_Built" ,"Year_Sold" ,"Sale_Price" ,"Neighborhood"]]

      Year_Built  Year_Sold  Sale_Price Neighborhood
2180        2008       2007      183850      Edwards

In [80]:
df_clean[df_clean["Neighborhood"] =="Edwards"][["Year_Built" ,"Year_Sold" ,"Sale_Price"]].describe()

        Year_Built    Year_Sold     Sale_Price
count   194.000000   194.000000     194.000000
mean   1956.938144  2007.798969  130843.381443
std      26.166392     1.325634   48030.405046
min    1900.000000  2006.000000   35000.000000
25%    1941.000000  2007.000000  103525.000000
50%    1954.000000  2008.000000  125000.000000
75%    1971.250000  2009.000000  144875.000000
max    2009.000000  2010.000000  415000.000000

In [81]:
df_clean["Sale_Price"].quantile([0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99])

0.01     61756.07
0.05     87500.00
0.25    129500.00
0.50    160000.00
0.75    213500.00
0.95    335000.00
0.99    456666.37
Name: Sale_Price, dtype: float64

In [61]:
df["Sale_Price"]

0       215000
1       105000
2       172000
3       244000
4       189900
         ...
2925    142500
2926    131000
2927    132000
2928    170000
2929    188000
Name: Sale_Price, Length: 2930, dtype: int64

In [62]:
df.head(5)

,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,Lot_Config,...,Fence,Misc_Feature,Misc_Val,Mo_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price,Longitude,Latitude
0,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,141,31770,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Corner,...,No_Fence,NaN,0,5,2010,WD,Normal,215000,-93.619754,42.054035
1,One_Story_1946_and_Newer_All_Styles,Residential_High_Density,80,11622,Pave,No_Alley_Access,Regular,Lvl,AllPub,Inside,...,Minimum_Privacy,NaN,0,6,2010,WD,Normal,105000,-93.619756,42.053014
2,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,81,14267,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Corner,...,No_Fence,Gar2,12500,6,2010,WD,Normal,172000,-93.619387,42.052659
3,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,93,11160,Pave,No_Alley_Access,Regular,Lvl,AllPub,Corner,...,No_Fence,NaN,0,4,2010,WD,Normal,244000,-93.617320,42.051245
4,Two_Story_1946_and_Newer,Residential_Low_Density,74,13830,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Inside,...,Minimum_Privacy,NaN,0,3,2010,WD,Normal,189900,-93.638933,42.060899

In [14]:
df.head()

,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,Lot_Config,...,Fence,Misc_Feature,Misc_Val,Mo_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price,Longitude,Latitude
0,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,141,31770,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Corner,...,No_Fence,NaN,0,5,2010,WD,Normal,215000,-93.619754,42.054035
1,One_Story_1946_and_Newer_All_Styles,Residential_High_Density,80,11622,Pave,No_Alley_Access,Regular,Lvl,AllPub,Inside,...,Minimum_Privacy,NaN,0,6,2010,WD,Normal,105000,-93.619756,42.053014
2,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,81,14267,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Corner,...,No_Fence,Gar2,12500,6,2010,WD,Normal,172000,-93.619387,42.052659
3,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,93,11160,Pave,No_Alley_Access,Regular,Lvl,AllPub,Corner,...,No_Fence,NaN,0,4,2010,WD,Normal,244000,-93.617320,42.051245
4,Two_Story_1946_and_Newer,Residential_Low_Density,74,13830,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Inside,...,Minimum_Privacy,NaN,0,3,2010,WD,Normal,189900,-93.638933,42.060899

In [15]:
df.describe()

,Lot_Frontage,Lot_Area,Year_Built,Year_Remod_Add,Mas_Vnr_Area,BsmtFin_SF_1,BsmtFin_SF_2,Bsmt_Unf_SF,Total_Bsmt_SF,First_Flr_SF,...,Enclosed_Porch,Three_season_porch,Screen_Porch,Pool_Area,Misc_Val,Mo_Sold,Year_Sold,Sale_Price,Longitude,Latitude
count,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,...,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,57.647782,10147.921843,1971.356314,1984.266553,101.096928,4.177474,49.705461,559.071672,1051.255631,1159.557679,...,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068,-93.642897,42.034482
std,33.499441,7880.017759,30.245361,20.860286,178.634545,2.233372,169.142089,439.540571,440.968018,391.890885,...,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357,0.025700,0.018410
min,0.000000,1300.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000,-93.693153,41.986498
25%,43.000000,7440.250000,1954.000000,1965.000000,0.000000,3.000000,0.000000,219.000000,793.000000,876.250000,...,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000,-93.660217,42.022088
50%,63.000000,9436.500000,1973.000000,1993.000000,0.000000,3.000000,0.000000,465.500000,990.000000,1084.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000,-93.641806,42.034662
75%,78.000000,11555.250000,2001.000000,2004.000000,162.750000,7.000000,0.000000,801.750000,1301.500000,1384.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000,-93.622113,42.049853
max,313.000000,215245.000000,2010.000000,2010.000000,1600.000000,7.000000,1526.000000,2336.000000,6110.000000,5095.000000,...,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000,-93.577427,42.063388

In [16]:
df.head()

,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,Lot_Config,...,Fence,Misc_Feature,Misc_Val,Mo_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price,Longitude,Latitude
0,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,141,31770,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Corner,...,No_Fence,NaN,0,5,2010,WD,Normal,215000,-93.619754,42.054035
1,One_Story_1946_and_Newer_All_Styles,Residential_High_Density,80,11622,Pave,No_Alley_Access,Regular,Lvl,AllPub,Inside,...,Minimum_Privacy,NaN,0,6,2010,WD,Normal,105000,-93.619756,42.053014
2,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,81,14267,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Corner,...,No_Fence,Gar2,12500,6,2010,WD,Normal,172000,-93.619387,42.052659
3,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,93,11160,Pave,No_Alley_Access,Regular,Lvl,AllPub,Corner,...,No_Fence,NaN,0,4,2010,WD,Normal,244000,-93.617320,42.051245
4,Two_Story_1946_and_Newer,Residential_Low_Density,74,13830,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Inside,...,Minimum_Privacy,NaN,0,3,2010,WD,Normal,189900,-93.638933,42.060899

In [17]:
profile = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "missing_count": df.isna().sum().values,
    "missing_percent": (
        df.isna().mean().mul(100).round(2).values
    ),
    "unique_count": df.nunique(dropna=False).values,
    "sample_value": [
        df[column].dropna().iloc[0]
        if df[column].notna().any()
        else None
        for column in df.columns
    ]
})

profile

,column,dtype,missing_count,missing_percent,unique_count,sample_value
0,MS_SubClass,object,0,0.0,16,One_Story_1946_and_Newer_All_Styles
1,MS_Zoning,object,0,0.0,7,Residential_Low_Density
2,Lot_Frontage,int64,0,0.0,129,141
3,Lot_Area,int64,0,0.0,1960,31770
4,Street,object,0,0.0,2,Pave
...,...,...,...,...,...,...
76,Sale_Type,object,0,0.0,10,WD
77,Sale_Condition,object,0,0.0,6,Normal
78,Sale_Price,int64,0,0.0,1032,215000
79,Longitude,float64,0,0.0,2776,-93.619754
80,Latitude,float64,0,0.0,2762,42.054035

In [18]:
len(df.columns)

81

In [19]:
df.select_dtypes(include = "number")

,Lot_Frontage,Lot_Area,Year_Built,Year_Remod_Add,Mas_Vnr_Area,BsmtFin_SF_1,BsmtFin_SF_2,Bsmt_Unf_SF,Total_Bsmt_SF,First_Flr_SF,...,Enclosed_Porch,Three_season_porch,Screen_Porch,Pool_Area,Misc_Val,Mo_Sold,Year_Sold,Sale_Price,Longitude,Latitude
0,141,31770,1960,1960,112,2,0,441,1080,1656,...,0,0,0,0,0,5,2010,215000,-93.619754,42.054035
1,80,11622,1961,1961,0,6,144,270,882,896,...,0,0,120,0,0,6,2010,105000,-93.619756,42.053014
2,81,14267,1958,1958,108,1,0,406,1329,1329,...,0,0,0,0,12500,6,2010,172000,-93.619387,42.052659
3,93,11160,1968,1968,0,1,0,1045,2110,2110,...,0,0,0,0,0,4,2010,244000,-93.617320,42.051245
4,74,13830,1997,1998,0,3,0,137,928,928,...,0,0,0,0,0,3,2010,189900,-93.638933,42.060899
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,37,7937,1984,1984,0,3,0,184,1003,1003,...,0,0,0,0,0,3,2006,142500,-93.604776,41.988964
2926,0,8885,1983,1983,0,2,324,239,864,902,...,0,0,0,0,0,6,2006,131000,-93.602680,41.988314
2927,62,10441,1992,1992,0,3,0,575,912,970,...,0,0,0,0,700,7,2006,132000,-93.606847,41.986510
2928,77,10010,1974,1975,0,1,123,195,1389,1389,...,0,0,0,0,0,4,2006,170000,-93.600190,41.990921
2929,74,9627,1993,1994,94,4,0,238,996,996,...,0,0,0,0,0,11,2006,188000,-93.599996,41.989265

In [20]:
df["Street"].duplicated().sum()

np.int64(2928)

In [21]:
df.describe()
df.describe(include="object")

,MS_SubClass,MS_Zoning,Street,Alley,Lot_Shape,Land_Contour,Utilities,Lot_Config,Land_Slope,Neighborhood,...,Garage_Type,Garage_Finish,Garage_Qual,Garage_Cond,Paved_Drive,Pool_QC,Fence,Misc_Feature,Sale_Type,Sale_Condition
count,2930,2930,2930,2930,2930,2930,2930,2930,2930,2930,...,2930,2930,2930,2930,2930,2930,2930,106,2930,2930
unique,16,7,2,3,4,4,3,5,3,28,...,7,4,6,6,3,5,5,5,10,6
top,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,Pave,No_Alley_Access,Regular,Lvl,AllPub,Inside,Gtl,North_Ames,...,Attchd,Unf,Typical,Typical,Paved,No_Pool,No_Fence,Shed,WD,Normal
freq,1079,2273,2918,2732,1859,2633,2927,2140,2789,443,...,1731,1231,2615,2665,2652,2917,2358,95,2536,2413

In [22]:
df.isna().sum()

MS_SubClass       0
MS_Zoning         0
Lot_Frontage      0
Lot_Area          0
Street            0
                 ..
Sale_Type         0
Sale_Condition    0
Sale_Price        0
Longitude         0
Latitude          0
Length: 81, dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.nunique().sort_values()

Central_Air          2
Street               2
Paved_Drive          3
Bsmt_Half_Bath       3
Utilities            3
                  ...
Bsmt_Unf_SF       1137
Gr_Liv_Area       1292
Lot_Area          1960
Latitude          2762
Longitude         2776
Length: 81, dtype: int64

In [25]:
df["Sale_Price"]

0       215000
1       105000
2       172000
3       244000
4       189900
         ...
2925    142500
2926    131000
2927    132000
2928    170000
2929    188000
Name: Sale_Price, Length: 2930, dtype: int64